# bott.el support for the GitLab protocol for CI
#
# Author:   Basil L. Contovounesios <contovob@tcd.ie>
# Homepage: https://gitlab.com/basil-conto/bott
#
# Written in 2019 by Basil L. Contovounesios <contovob@tcd.ie>.
#
# This file is NOT part of GNU Emacs.
#
# To the extent possible under law, the author has dedicated all
# copyright and related and neighbouring rights to this software to
# the public domain worldwide.  This software is distributed without
# any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication
# along with this software.  If not, see
# <https://creativecommons.org/publicdomain/zero/1.0/>.

image: debian:bullseye-backports

variables:
  GIT_STRATEGY: clone

before_script:
  - apt-get --quiet update
  - apt-get --quiet --yes install curl emacs-nox make yt-dlp

test:
  script:
    - emacs --version
    - yt-dlp --version
    - curl --version
    - make test
